### ISSUE TITLE
how to host IPF on tomcat

### ISSUE THREAD

**Issue by cribello** [sayan801/ipf#5]
[emc-xdsb-repository-with-ipf.pdf](https://github.com/sayan801/ipf/files/793130/emc-xdsb-repository-with-ipf.pdf)
[emc-xca-with-IPF.pdf](https://github.com/sayan801/ipf/files/793131/emc-xca-with-IPF.pdf)

**Comment by sayan801** [comment]
# sudo java -jar IPF-XDS.jar

````
Feb 22, 2017 5:31:22 PM org.apache.catalina.core.StandardHost setAppBase
WARNING: Using an empty string for appBase on host [localhost] will set it to CATALINA_BASE, which is a bad idea
Feb 22, 2017 5:31:51 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-9091"]
Feb 22, 2017 5:31:57 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Feb 22, 2017 5:31:58 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Feb 22, 2017 5:31:58 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.4
Feb 22, 2017 5:32:07 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:911)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.StandardRoot@393266eb]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:111)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:141)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4831)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4963)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 6 more
Caused by: java.lang.Error: factory already defined
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1112)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:128)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:51)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:75)
	at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:679)
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:662)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	... 10 more

Feb 22, 2017 5:32:07 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:911)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:791)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:356)
	at org.openehealth.ipf.commons.ihe.ws.server.TomcatServer.start(TomcatServer.java:98)
	at org.openehealth.ipf.commons.ihe.ws.server.TomcatServer$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.openehealth.ipf.tutorials.xds.Server.main(Server.groovy:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 6 more

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.AssertionError: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.openehealth.ipf.commons.ihe.ws.server.TomcatServer.start(TomcatServer.java:102)
	at org.openehealth.ipf.commons.ihe.ws.server.TomcatServer$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.openehealth.ipf.tutorials.xds.Server.main(Server.groovy:56)
	... 5 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:356)
	at org.openehealth.ipf.commons.ihe.ws.server.TomcatServer.start(TomcatServer.java:98)
	... 10 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:791)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 12 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 14 more
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 16 more
````

**Comment by sunandit-cribello** [comment]
# Steps to create WAR file creation for JAVA based project 

## Creation of WEB-INF folder, web.xml file and required modification in pom.xml
* 1. We consider JAVA based project, which is given in issue https://github.com/cribello/myCuratio-IHE-actors/issues/10
* 2. Follow the steps below:-
```
$ cd home/user/jarfiles/ipf/tutorials/xds/
$ ls
$ gedit pom.xml
Inside pom.xml do the following changes: 
1. <modelVersion>4.0.0</modelVersion>
    <artifactId>ipf-tutorials-xds</artifactId>
    <name>ipf-tutorials-xds</name>
    <!--<packaging>jar</packaging> --> # Disable .jar file creation option 
    <packaging>war</packaging>   # Enable .jar file creation option 
    <url>${site.url}/${project.artifactId}</url>

2. Add the following apache-maven plugin for maven build
<project>

.....

<build>
        <plugins>
.....
<plugin>            
  			<groupId>org.apache.maven.plugins</groupId>
 			 <artifactId>maven-war-plugin</artifactId>
  			<configuration>
    					<webXml>src/main/WEB-INF/web.xml</webXml>        
  			</configuration>
		</plugin>
        </plugins>
</project>
$ pwd
/home/user/jarfiles/ipf/tutorials/xds
$ cd src/main/
$ mkdir WEB-INF
$ gedit web.xml
-- add following content
<!DOCTYPE web-app PUBLIC
 "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
 "http://java.sun.com/dtd/web-app_2_3.dtd" >

<web-app>
  <display-name>Archetype Created Web Application</display-name>
</web-app>

```
## Creation of clean Maven build of modified JAVA project
```
$ pwd
/home/user/jarfiles/ipf/tutorials/xds
$ mvn clean install
```
Build success message:
![image](https://cloud.githubusercontent.com/assets/6313450/23254369/d9959e5a-f9dd-11e6-8638-2e01c26b3826.png)

##  Creation of XDS as Eclipse project. Here we use Eclipse Version: Neon.2 Release (4.6.2)

```
$ pwd
/home/user/jarfiles/ipf/tutorials/xds
$ mvn eclipse:eclipse

```
* This command provides a stable deployment of XDS on Ecilpse and after successful deployment it shows following message:
![image](https://cloud.githubusercontent.com/assets/6313450/23254643/bce00dc6-f9de-11e6-801e-a57914fd87a3.png)


* **Note:**
* 1. if above command shows : **File /home/user/jarfiles/ipf/tutorials/xds/.project already exists. Additional settings will be preserved, run mvn eclipse:clean if you want old settings to be removed.** then
```
$ mvn eclipse:clean
$ mvn eclipse:eclipse

```

**Comment by sayan801** [comment]
FAIL - Application at context path /ipf-tutorials could not be started
FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/ipf-tutorials]]
